### ISSUE TITLE
learn ide stop working on this lab

### ISSUE THREAD

**Issue by donveechi** [learn-co-curriculum/javascript-intro-to-looping#26]
whenever i type learn and press enter the program crash each and every time on this lab

**Comment by iamnotsosure** [comment]
I'm running into a similar issue as well. when I initially forked this lab, I was given the lab name "javascript-intro-to-looping-bootcamp-prep-000", but when I follow the repo link, the lab does not exist. However, when I bring up an issue in this lab, it brings me to this lab titled "javascript-intro-to-looping". 

I haven't been able to submit this lab because the Learn IDE tells me that I haven't forked this lab yet even though I have. Any help would be greatly appreciated!

**Comment by donveechi** [comment]
have you fixed the issue or your still having it?

**Comment by iamnotsosure** [comment]
I'm still having the issue. I tried changing the master folder name to "javascript-intro-to-looping" as we see it here, but it tells me that I haven't forked this lessen yet (even though I have). I'm just gonna keep going on with the lessons for now!

**Comment by JessRudder** [comment]
@donveechi @iamnotsosure please reach out to Learn Experts using "Ask a Question" in Learn if you are still having this issue.  They will help you debug it in real time.
