### ISSUE TITLE
there is something wrong with the length function in the tdd

### ISSUE THREAD

**Issue by blydiet** [learn-co-curriculum/javascript-intro-to-looping#33]

**Comment by gj** [comment]
Hi there,

Would you mind providing a bit more detail about the issue? Things that are especially useful:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 🙂

**Comment by gj** [comment]
Hi there,

This issue is being closed now as stale. If the issue is encountered again, please first consult the [Learn Help Center](http://help.learn.co/) and the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature. If neither of those options resolves the problem and you still feel that this is an issue with the curriculum, please reopen this issue and provide as much detail as possible:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 🙂
