### ISSUE TITLE
Missing "s" from gift

### ISSUE THREAD

**Issue by BaronLip** [learn-co-curriculum/javascript-intro-to-looping#64]
I'm pretty sure there's supposed to be an "s" after "gift" in this portion of the code:

function wrapGift(gift**s**) {
  console.log(`Wrapped ${gift**s**} and added a bow!`);
}

![missingS](https://user-images.githubusercontent.com/45054120/57007695-3a6aba80-6bb0-11e9-9a6b-8f8eca98cc70.png)

**Comment by sylwiavargas** [comment]
Thank you for flagging this down. In this case, the parameter passed into the function on line 3 should be "gift" because it refers to one specific gift, and not the whole array. Undreneath the function (in the lesson), you will see that the function is then invoked by passing in an instance of a specific element of the gifts array.
